import os

def canSum(targetSum, numbers):
    """Return True if the targetSum can be generated by using elements from
    numbers. Return False if otherwise.
    """
    # initialize table
    table = [False] * (targetSum + 1)
    
    # assign default values
    table[0] = True
    for num in numbers:
        table[num] = True

    # iterate through the table
    for i in range(len(table)):
        # check if the current element is True --> assign values to table
        if table[i] == True:
            for num in numbers:
                # check out of bound
                if (i + num) <= targetSum:
                    table[i + num] = True

    print(table)
    return table[targetSum]

if __name__ == '__main__':
    os.system('cls')
    print(canSum(7, [2, 3]))            # --> True
    print(canSum(7, [5, 3, 4, 7]))      # --> True
    print(canSum(7, [2, 4]))            # --> False
    print(canSum(8, [2, 3, 5]))         # --> True
    print(canSum(300, [7, 14]))         # --> False